name: PR Title Validation

on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  title-check:
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR Title Format
        uses: actions/github-script@v6
        with:
          script: |
            const title = context.payload.pull_request?.title;
            if (!title) {
              core.setFailed('❌ Pull request title is required.');
              return;
            }

            const regex = /^[a-zA-Z]+(\([a-zA-Z]+\))?: .+/;
            const allowedPrefixes = ['feat', 'fix', 'refac', 'chore', 'tool'];

            // 1. Validate format matches regex
            if (!regex.test(title)) {
              core.setFailed(
                [
                  '❌ Invalid PR title format.',
                  'Expected format: <prefix>(<optional scope>): <description>',
                  'Examples:',
                  '  • feat: add get prompt api',
                  '  • fix(napi): resolve bug'
                ].join('\n')
              );
              return;
            }

            // 2. Validate prefix is one of the allowed types
            const prefix = title.split(':')[0].split('(')[0];
            if (!allowedPrefixes.includes(prefix)) {
              core.setFailed(
                `❌ Invalid PR prefix "${prefix}".\nAllowed prefixes: ${allowedPrefixes.join(', ')}`
              );
              return;
            }

            core.info(`✅ PR title "${title}" looks good!`);
